use_frameworks!

target 'APManager_Example' do
  pod 'APManager', :path => '../'

  target 'APManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
